-- Esquinas leidas del mapa "Territorio Peralta Ramos" (180 puntos de salida tipo ESQUINA).
-- Cada esquina se relaciona con los territorios que la tocan, del que mas manzanas tiene en la esquina al que menos.
-- Aditiva e idempotente: solo crea puntos cuya direccion todavia no existe (no modifica ni borra los que ya cargaste)
-- y solo asocia territorios a los puntos que crea. Requiere fase-23-departure-point-kind.sql.
-- Zona centro (14, 16, 17): ver docs/ESQUINAS_MAPA.md (revisar antes de usar).
-- Todas las esquinas quedan disponibles de lunes a viernes (available_days = 1..5): entre semana se usan esquinas.

begin;

create temp table _esquinas (address text not null, territory_number integer not null, sort_order integer not null) on commit drop;

insert into _esquinas (address, territory_number, sort_order) values
  ('Funes y Larrea', 10, 0),
  ('Funes y Vieytes', 10, 0),
  ('Funes y Paso', 10, 0),
  ('Funes y Paso', 6, 1),
  ('Funes y Laprida', 6, 0),
  ('Funes y Almafuerte', 1, 0),
  ('Funes y Almafuerte', 6, 1),
  ('Funes y Formosa', 1, 0),
  ('Funes y Matheu', 1, 0),
  ('Guido y Larrea', 10, 0),
  ('Guido y Vieytes', 10, 0),
  ('Guido y Paso', 6, 0),
  ('Guido y Paso', 10, 1),
  ('Guido y Laprida', 6, 0),
  ('Guido y Almafuerte', 1, 0),
  ('Guido y Almafuerte', 6, 1),
  ('Guido y Formosa', 1, 0),
  ('Guido y Matheu', 1, 0),
  ('Dorrego y Larrea', 10, 0),
  ('Dorrego y Larrea', 11, 1),
  ('Dorrego y Vieytes', 10, 0),
  ('Dorrego y Vieytes', 11, 1),
  ('Dorrego y Paso', 6, 0),
  ('Dorrego y Paso', 7, 1),
  ('Dorrego y Paso', 10, 2),
  ('Dorrego y Paso', 11, 3),
  ('Dorrego y Laprida', 6, 0),
  ('Dorrego y Laprida', 7, 1),
  ('Dorrego y Almafuerte', 1, 0),
  ('Dorrego y Almafuerte', 3, 1),
  ('Dorrego y Almafuerte', 6, 2),
  ('Dorrego y Almafuerte', 7, 3),
  ('Dorrego y Formosa', 1, 0),
  ('Dorrego y Formosa', 3, 1),
  ('Dorrego y Matheu', 1, 0),
  ('Dorrego y Matheu', 2, 1),
  ('Dorrego y Matheu', 3, 2),
  ('14 de Julio y Larrea', 11, 0),
  ('14 de Julio y Vieytes', 11, 0),
  ('14 de Julio y Paso', 7, 0),
  ('14 de Julio y Paso', 11, 1),
  ('14 de Julio y Laprida', 7, 0),
  ('14 de Julio y Almafuerte', 3, 0),
  ('14 de Julio y Almafuerte', 7, 1),
  ('14 de Julio y Formosa', 3, 0),
  ('14 de Julio y Matheu', 2, 0),
  ('14 de Julio y Matheu', 3, 1),
  ('20 de Septiembre y Larrea', 12, 0),
  ('20 de Septiembre y Larrea', 11, 1),
  ('20 de Septiembre y Vieytes', 11, 0),
  ('20 de Septiembre y Vieytes', 12, 1),
  ('20 de Septiembre y Paso', 7, 0),
  ('20 de Septiembre y Paso', 8, 1),
  ('20 de Septiembre y Paso', 11, 2),
  ('20 de Septiembre y Paso', 12, 3),
  ('20 de Septiembre y Laprida', 7, 0),
  ('20 de Septiembre y Laprida', 8, 1),
  ('20 de Septiembre y Almafuerte', 3, 0),
  ('20 de Septiembre y Almafuerte', 4, 1),
  ('20 de Septiembre y Almafuerte', 7, 2),
  ('20 de Septiembre y Almafuerte', 8, 3),
  ('20 de Septiembre y Formosa', 3, 0),
  ('20 de Septiembre y Formosa', 4, 1),
  ('20 de Septiembre y Matheu', 2, 0),
  ('20 de Septiembre y Matheu', 3, 1),
  ('20 de Septiembre y Matheu', 4, 2),
  ('España y Larrea', 12, 0),
  ('España y Vieytes', 12, 0),
  ('España y Paso', 8, 0),
  ('España y Paso', 12, 1),
  ('España y Laprida', 8, 0),
  ('España y Almafuerte', 4, 0),
  ('España y Almafuerte', 8, 1),
  ('España y Formosa', 4, 0),
  ('España y Matheu', 2, 0),
  ('España y Matheu', 4, 1),
  ('Jujuy y Larrea', 12, 0),
  ('Jujuy y Larrea', 13, 1),
  ('Jujuy y Vieytes', 12, 0),
  ('Jujuy y Vieytes', 13, 1),
  ('Jujuy y Paso', 8, 0),
  ('Jujuy y Paso', 9, 1),
  ('Jujuy y Paso', 12, 2),
  ('Jujuy y Paso', 13, 3),
  ('Jujuy y Laprida', 8, 0),
  ('Jujuy y Laprida', 9, 1),
  ('Jujuy y Almafuerte', 4, 0),
  ('Jujuy y Almafuerte', 5, 1),
  ('Jujuy y Almafuerte', 8, 2),
  ('Jujuy y Almafuerte', 9, 3),
  ('Jujuy y Formosa', 4, 0),
  ('Jujuy y Formosa', 5, 1),
  ('Jujuy y Matheu', 2, 0),
  ('Jujuy y Matheu', 4, 1),
  ('Jujuy y Matheu', 5, 2),
  ('Salta y Larrea', 13, 0),
  ('Salta y Vieytes', 13, 0),
  ('Salta y Paso', 9, 0),
  ('Salta y Paso', 13, 1),
  ('Salta y Laprida', 9, 0),
  ('Salta y Almafuerte', 5, 0),
  ('Salta y Almafuerte', 9, 1),
  ('Salta y Formosa', 5, 0),
  ('Salta y Matheu', 5, 0),
  ('Independencia y Larrea', 13, 0),
  ('Independencia y Vieytes', 13, 0),
  ('Independencia y Paso', 9, 0),
  ('Independencia y Paso', 13, 1),
  ('Independencia y Laprida', 9, 0),
  ('Independencia y Almafuerte', 5, 0),
  ('Independencia y Almafuerte', 9, 1),
  ('Independencia y Formosa', 5, 0),
  ('Independencia y Matheu', 5, 0),
  ('De los Deportes y Irala', 16, 0),
  ('De los Deportes y Ayolas', 16, 0),
  ('De los Deportes y Magallanes', 14, 0),
  ('De los Deportes y Magallanes', 16, 1),
  ('De los Deportes y 12 de Octubre', 14, 0),
  ('V. del Mar y Irala', 16, 0),
  ('V. del Mar y Ayolas', 16, 0),
  ('V. del Mar y Magallanes', 14, 0),
  ('V. del Mar y Magallanes', 16, 1),
  ('V. del Mar y 12 de Octubre', 14, 0),
  ('V. del Mar y El Cano', 14, 0),
  ('Friuli y Irala', 16, 0),
  ('Friuli y Irala', 17, 1),
  ('Friuli y Ayolas', 16, 0),
  ('Friuli y Ayolas', 17, 1),
  ('Friuli y Magallanes', 17, 0),
  ('Friuli y Magallanes', 14, 1),
  ('Friuli y Magallanes', 16, 2),
  ('Friuli y 12 de Octubre', 14, 0),
  ('Friuli y 12 de Octubre', 17, 1),
  ('Friuli y El Cano', 14, 0),
  ('Friuli y El Cano', 17, 1),
  ('Friuli y Gaboto', 14, 0),
  ('L. de la Torre y Irala', 17, 0),
  ('L. de la Torre y Irala', 18, 1),
  ('L. de la Torre y Ayolas', 17, 0),
  ('L. de la Torre y Ayolas', 18, 1),
  ('L. de la Torre y Magallanes', 17, 0),
  ('L. de la Torre y Magallanes', 18, 1),
  ('L. de la Torre y 12 de Octubre', 17, 0),
  ('L. de la Torre y El Cano', 14, 0),
  ('L. de la Torre y El Cano', 17, 1),
  ('L. de la Torre y Gaboto', 14, 0),
  ('G. Chavez y Irala', 18, 0),
  ('G. Chavez y Ayolas', 18, 0),
  ('G. Chavez y Magallanes', 18, 0),
  ('G. Chavez y Magallanes', 19, 1),
  ('G. Chavez y 12 de Octubre', 19, 0),
  ('G. Chavez y El Cano', 15, 0),
  ('G. Chavez y El Cano', 19, 1),
  ('G. Chavez y Gaboto', 15, 0),
  ('G. Chavez y Solis', 15, 0),
  ('C. Villar y Irala', 18, 0),
  ('C. Villar y Ayolas', 18, 0),
  ('C. Villar y Magallanes', 18, 0),
  ('C. Villar y Magallanes', 19, 1),
  ('C. Villar y 12 de Octubre', 19, 0),
  ('C. Villar y El Cano', 15, 0),
  ('C. Villar y El Cano', 19, 1),
  ('C. Villar y Gaboto', 15, 0),
  ('C. Villar y Solis', 15, 0),
  ('P. Ramos y Vertiz', 32, 0),
  ('P. Ramos y San Salvador', 32, 0),
  ('P. Ramos y Guanahani', 32, 0),
  ('P. Ramos y Hernandarias', 32, 0),
  ('P. Ramos y O. Zarate', 27, 0),
  ('P. Ramos y O. Zarate', 32, 1),
  ('P. Ramos y Irala', 27, 0),
  ('P. Ramos y Irala', 18, 1),
  ('P. Ramos y Ayolas', 18, 0),
  ('P. Ramos y Ayolas', 27, 1),
  ('P. Ramos y Magallanes', 27, 0),
  ('P. Ramos y Magallanes', 18, 1),
  ('P. Ramos y Magallanes', 19, 2),
  ('P. Ramos y 12 de Octubre', 19, 0),
  ('P. Ramos y 12 de Octubre', 22, 1),
  ('P. Ramos y 12 de Octubre', 27, 2),
  ('P. Ramos y El Cano', 22, 0),
  ('P. Ramos y El Cano', 15, 1),
  ('P. Ramos y El Cano', 19, 2),
  ('P. Ramos y Gaboto', 15, 0),
  ('P. Ramos y Gaboto', 22, 1),
  ('P. Ramos y Solis', 15, 0),
  ('P. Ramos y Solis', 22, 1),
  ('F. Sanchez y Vertiz', 32, 0),
  ('F. Sanchez y Vertiz', 35, 1),
  ('F. Sanchez y San Salvador', 32, 0),
  ('F. Sanchez y San Salvador', 35, 1),
  ('F. Sanchez y Guanahani', 32, 0),
  ('F. Sanchez y Guanahani', 33, 1),
  ('F. Sanchez y Guanahani', 35, 2),
  ('F. Sanchez y Hernandarias', 32, 0),
  ('F. Sanchez y Hernandarias', 33, 1),
  ('F. Sanchez y O. Zarate', 27, 0),
  ('F. Sanchez y O. Zarate', 30, 1),
  ('F. Sanchez y O. Zarate', 32, 2),
  ('F. Sanchez y O. Zarate', 33, 3),
  ('F. Sanchez y Irala', 27, 0),
  ('F. Sanchez y Irala', 30, 1),
  ('F. Sanchez y Ayolas', 27, 0),
  ('F. Sanchez y Ayolas', 28, 1),
  ('F. Sanchez y Ayolas', 30, 2),
  ('F. Sanchez y Magallanes', 27, 0),
  ('F. Sanchez y Magallanes', 28, 1),
  ('F. Sanchez y 12 de Octubre', 22, 0),
  ('F. Sanchez y 12 de Octubre', 25, 1),
  ('F. Sanchez y 12 de Octubre', 27, 2),
  ('F. Sanchez y 12 de Octubre', 28, 3),
  ('F. Sanchez y El Cano', 22, 0),
  ('F. Sanchez y El Cano', 25, 1),
  ('F. Sanchez y Gaboto', 22, 0),
  ('F. Sanchez y Gaboto', 23, 1),
  ('F. Sanchez y Gaboto', 25, 2),
  ('F. Sanchez y Solis', 22, 0),
  ('F. Sanchez y Solis', 23, 1),
  ('J. Manzo y Vertiz', 35, 0),
  ('J. Manzo y San Salvador', 35, 0),
  ('J. Manzo y Guanahani', 33, 0),
  ('J. Manzo y Guanahani', 35, 1),
  ('J. Manzo y Hernandarias', 33, 0),
  ('J. Manzo y O. Zarate', 30, 0),
  ('J. Manzo y O. Zarate', 33, 1),
  ('J. Manzo y Irala', 30, 0),
  ('J. Manzo y Ayolas', 28, 0),
  ('J. Manzo y Ayolas', 30, 1),
  ('J. Manzo y Magallanes', 28, 0),
  ('J. Manzo y 12 de Octubre', 25, 0),
  ('J. Manzo y 12 de Octubre', 28, 1),
  ('J. Manzo y El Cano', 25, 0),
  ('J. Manzo y Gaboto', 23, 0),
  ('J. Manzo y Gaboto', 25, 1),
  ('J. Manzo y Solis', 23, 0),
  ('Bestoso y Vertiz', 35, 0),
  ('Bestoso y Vertiz', 36, 1),
  ('Bestoso y San Salvador', 35, 0),
  ('Bestoso y San Salvador', 36, 1),
  ('Bestoso y Guanahani', 33, 0),
  ('Bestoso y Guanahani', 34, 1),
  ('Bestoso y Guanahani', 35, 2),
  ('Bestoso y Guanahani', 36, 3),
  ('Bestoso y Hernandarias', 33, 0),
  ('Bestoso y Hernandarias', 34, 1),
  ('Bestoso y O. Zarate', 30, 0),
  ('Bestoso y O. Zarate', 31, 1),
  ('Bestoso y O. Zarate', 33, 2),
  ('Bestoso y O. Zarate', 34, 3),
  ('Bestoso y Irala', 30, 0),
  ('Bestoso y Irala', 31, 1),
  ('Bestoso y Ayolas', 28, 0),
  ('Bestoso y Ayolas', 29, 1),
  ('Bestoso y Ayolas', 30, 2),
  ('Bestoso y Ayolas', 31, 3),
  ('Bestoso y Magallanes', 28, 0),
  ('Bestoso y Magallanes', 29, 1),
  ('Bestoso y 12 de Octubre', 25, 0),
  ('Bestoso y 12 de Octubre', 26, 1),
  ('Bestoso y 12 de Octubre', 28, 2),
  ('Bestoso y 12 de Octubre', 29, 3),
  ('Bestoso y El Cano', 25, 0),
  ('Bestoso y El Cano', 26, 1),
  ('Bestoso y Gaboto', 23, 0),
  ('Bestoso y Gaboto', 24, 1),
  ('Bestoso y Gaboto', 25, 2),
  ('Bestoso y Gaboto', 26, 3),
  ('Bestoso y Solis', 23, 0),
  ('Bestoso y Solis', 24, 1),
  ('Valentini y Vertiz', 36, 0),
  ('Valentini y San Salvador', 36, 0),
  ('Valentini y Guanahani', 36, 0),
  ('Valentini y Guanahani', 34, 1),
  ('Valentini y Hernandarias', 34, 0),
  ('Valentini y O. Zarate', 31, 0),
  ('Valentini y O. Zarate', 34, 1),
  ('Valentini y Irala', 31, 0),
  ('Valentini y Ayolas', 29, 0),
  ('Valentini y Ayolas', 31, 1),
  ('Valentini y Magallanes', 29, 0),
  ('Valentini y 12 de Octubre', 26, 0),
  ('Valentini y 12 de Octubre', 29, 1),
  ('Valentini y El Cano', 26, 0),
  ('Valentini y Gaboto', 24, 0),
  ('Valentini y Gaboto', 26, 1),
  ('Valentini y Solis', 24, 0),
  ('Dellepiane y Vertiz', 36, 0),
  ('Dellepiane y San Salvador', 36, 0),
  ('Dellepiane y Guanahani', 36, 0),
  ('Dellepiane y Hernandarias', 34, 0),
  ('Dellepiane y O. Zarate', 31, 0),
  ('Dellepiane y O. Zarate', 34, 1),
  ('Dellepiane y Irala', 31, 0),
  ('Dellepiane y Ayolas', 29, 0),
  ('Dellepiane y Ayolas', 31, 1),
  ('Dellepiane y Magallanes', 29, 0),
  ('Dellepiane y 12 de Octubre', 26, 0),
  ('Dellepiane y 12 de Octubre', 29, 1),
  ('Dellepiane y El Cano', 26, 0),
  ('Dellepiane y Gaboto', 24, 0),
  ('Dellepiane y Gaboto', 26, 1),
  ('Dellepiane y Solis', 24, 0),
  ('Catamarca y JB. Justo', 20, 0),
  ('Catamarca y Larrea', 20, 0),
  ('La Rioja y JB. Justo', 20, 0),
  ('La Rioja y Larrea', 20, 0),
  ('Azcuenaga y JB. Justo', 20, 0),
  ('Azcuenaga y JB. Justo', 21, 1),
  ('Azcuenaga y Larrea', 20, 0),
  ('Azcuenaga y Larrea', 21, 1),
  ('Mitre y JB. Justo', 21, 0),
  ('Mitre y Larrea', 21, 0),
  ('San Luis y JB. Justo', 21, 0),
  ('San Luis y Larrea', 21, 0);

with nuevas as (
  insert into public.departure_points (name, address, kind)
  select '', s.address, 'ESQUINA'
  from (select distinct address from _esquinas) s
  where not exists (
    select 1 from public.departure_points d where lower(btrim(d.address)) = lower(s.address)
  )
  returning id, address
)
insert into public.departure_point_territories (departure_point_id, territory_id, sort_order)
select n.id, t.id, e.sort_order
from nuevas n
join _esquinas e on e.address = n.address
join public.territories t on t.number = e.territory_number;

-- Lunes a viernes para estas esquinas (nuevas o ya cargadas). No pisa dias que hayas elegido a mano:
-- solo toca las que siguen sin dias definidos.
update public.departure_points
set available_days = '{1,2,3,4,5}', updated_at = now()
where kind = 'ESQUINA'
  and available_days = '{}'::integer[]
  and lower(btrim(address)) in (select lower(address) from _esquinas);

commit;
